/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PdexCoreInterface extends Interface {
  functions: {
    registerCompany: TypedFunctionDescription<{
      encode([_companyAddress, _sharesAmount, _initialSharePrice, _riskRatio]: [
        string,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    approveBroker: TypedFunctionDescription<{
      encode([_brokerAddress]: [string]): string;
    }>;

    companiesProfiles: TypedFunctionDescription<{
      encode([]: [string]): string;
    }>;

    stakeProfit: TypedFunctionDescription<{
      encode([_companyAddress]: [string]): string;
    }>;

    registerInvestor: TypedFunctionDescription<{
      encode([_investorAddress, _maxRiskRatio]: [string, BigNumberish]): string;
    }>;

    shares: TypedFunctionDescription<{ encode([,]: [string, string]): string }>;

    claimPayout: TypedFunctionDescription<{
      encode([_amount]: [BigNumberish]): string;
    }>;
  };

  events: {
    BrokerApproved: TypedEventDescription<{
      encodeTopics([brokerAddress]: [null]): string[];
    }>;

    CompanyRegistered: TypedEventDescription<{
      encodeTopics([byBroker, companyAddress, sharesSupply, sharePrice]: [
        string | null,
        null,
        null,
        null
      ]): string[];
    }>;

    InvestorRegistered: TypedEventDescription<{
      encodeTopics([byBroker, investorAddress, maxRiskRatio]: [
        string | null,
        null,
        null
      ]): string[];
    }>;

    PayoutClaimed: TypedEventDescription<{
      encodeTopics([byCompany, amount]: [string | null, null]): string[];
    }>;

    ProfitPayout: TypedEventDescription<{
      encodeTopics([fromCompany, amount, by]: [
        string | null,
        null,
        string | null
      ]): string[];
    }>;
  };
}

export class PdexCore extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PdexCore;
  attach(addressOrName: string): PdexCore;
  deployed(): Promise<PdexCore>;

  on(event: EventFilter | string, listener: Listener): PdexCore;
  once(event: EventFilter | string, listener: Listener): PdexCore;
  addListener(eventName: EventFilter | string, listener: Listener): PdexCore;
  removeAllListeners(eventName: EventFilter | string): PdexCore;
  removeListener(eventName: any, listener: Listener): PdexCore;

  interface: PdexCoreInterface;

  functions: {
    registerCompany(
      _companyAddress: string,
      _sharesAmount: BigNumberish,
      _initialSharePrice: BigNumberish,
      _riskRatio: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    approveBroker(
      _brokerAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    companiesProfiles(
      arg0: string
    ): Promise<{
      approved: boolean;
      fromBroker: string;
      sharesSupply: BigNumber;
      initialSharePrice: BigNumber;
      shareRiskRatio: BigNumber;
      raisedFunds: BigNumber;
      payoutAmount: BigNumber;
      0: boolean;
      1: string;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
    }>;

    stakeProfit(
      _companyAddress: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    registerInvestor(
      _investorAddress: string,
      _maxRiskRatio: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    shares(arg0: string, arg1: string): Promise<BigNumber>;

    claimPayout(
      _amount: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  registerCompany(
    _companyAddress: string,
    _sharesAmount: BigNumberish,
    _initialSharePrice: BigNumberish,
    _riskRatio: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  approveBroker(
    _brokerAddress: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  companiesProfiles(
    arg0: string
  ): Promise<{
    approved: boolean;
    fromBroker: string;
    sharesSupply: BigNumber;
    initialSharePrice: BigNumber;
    shareRiskRatio: BigNumber;
    raisedFunds: BigNumber;
    payoutAmount: BigNumber;
    0: boolean;
    1: string;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
  }>;

  stakeProfit(
    _companyAddress: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  registerInvestor(
    _investorAddress: string,
    _maxRiskRatio: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  shares(arg0: string, arg1: string): Promise<BigNumber>;

  claimPayout(
    _amount: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    BrokerApproved(brokerAddress: null): EventFilter;

    CompanyRegistered(
      byBroker: string | null,
      companyAddress: null,
      sharesSupply: null,
      sharePrice: null
    ): EventFilter;

    InvestorRegistered(
      byBroker: string | null,
      investorAddress: null,
      maxRiskRatio: null
    ): EventFilter;

    PayoutClaimed(byCompany: string | null, amount: null): EventFilter;

    ProfitPayout(
      fromCompany: string | null,
      amount: null,
      by: string | null
    ): EventFilter;
  };

  estimate: {
    registerCompany(
      _companyAddress: string,
      _sharesAmount: BigNumberish,
      _initialSharePrice: BigNumberish,
      _riskRatio: BigNumberish
    ): Promise<BigNumber>;

    approveBroker(_brokerAddress: string): Promise<BigNumber>;

    companiesProfiles(arg0: string): Promise<BigNumber>;

    stakeProfit(_companyAddress: string): Promise<BigNumber>;

    registerInvestor(
      _investorAddress: string,
      _maxRiskRatio: BigNumberish
    ): Promise<BigNumber>;

    shares(arg0: string, arg1: string): Promise<BigNumber>;

    claimPayout(_amount: BigNumberish): Promise<BigNumber>;
  };
}
